@startuml
!include ../../style.puml

actor Tester

participant "GM : GameManager" as GM
participant "C : SpcaeShip" as SS

Tester -> GM : TakeTurn()
activate GM

alt Solar Storm Active

GM -> GM : CreateStormOn = false;
GM -> SS ++ : SolarFlare()
GM <-- SS --

end

GM -> SS ++ : RoundEnd()
GM <-- SS --

Tester <-- GM
deactivate GM

@enduml