@startuml
hide footbox
autonumber "0:"
skinparam sequenceMessageAlign center

participant gm as gm <<GameManager>>

participant sc as Scene <<Scene>>

participant Entity as "en" <<Entity>>

gm -> Scene ++ : solarFlare(pos, radius)

loop for each ent in entities

    Scene -> Entity ++ : getPos();
    return : position

    opt if position is inside circle(pos,radius)
        Scene -> Entity ++ : solarFlare();
        return
    end

end

return

@enduml