@startuml
actor Tester as Tester<<SpaceShip>>
participant recipe as recipe <<RobotRecipe>>
participant s as s <<SpaceShip>>
participant inventory as inventory <<Inventory>>
participant asteroid as asteroid <<Asteroid>>
participant inv as inv <<Inventory>>
collections item as item <<Item>>
participant p as p <<Person>>
participant robot as robot <<Robot>>

title SpaceShip can craft robot

Tester-> recipe++: Craft(s)

recipe -> s++: GetAsteroid()
s --> recipe--: a

recipe -> s++: GetInventory()
s --> recipe--: inv

group loop: input check[for each item in recipe.input]

    recipe -> inventory++: RemoveItem(item)
    inventory-->recipe--: x

    recipe -> item++: Reduce(x)
    item --> recipe--: 

    group opt [not satisfied]
        recipe -> asteroid++: GetInventory()
        asteroid --> recipe--: inv

        recipe -> inv++: RemoveItem(i)
        inv--> recipe--: y
    end
end
recipe -> recipe++: MakeResult(s)
recipe -> s++: GetOwner()

s--> recipe--: p
recipe --> robot--: <<create>> Robot(p,asteroid)

recipe --> Tester: 

caption A recept levonja a nyersanyagokat a megfelelő helyekről (telepes vagy aszteroida raktárából, kapacitástól függően), \n majd elkészíti a robotot és elhelyezi a megfelelő aszteroidán. 
@enduml