@startuml

actor Tester as Tester
participant s as s <<SpaceShip>>
participant recipe as recipe <<RobotRecipe>>


title SpaceShip can't craft robot

Tester -> s++: Craft(recipe)

s-> recipe++: CanCraft(s)
recipe --> s --: false

s--> Tester: false

caption  A telepes szeretne létrehozni egy robotot a kibányászott nyersanyagokkal. \n A készítés előtti ellenőrzés során kiderült, hogy nem lehet előállítani a robotot, \n ezért a készítést végző függvény meg sem hívódik. 


@enduml