@startuml
actor Tester as Tester <<SpaceShip>>
participant recipe as recipe <<RobotRecipe>>
participant s as s <<SpaceShip>>
participant inv as inv <<Inventory>>
participant a as a <<Asteroid>>
participant inventory as inventory <<Inventory>>
collections item as item <<Item>>
collections aItem as aItem <<Item>>

title SpaceShip can't craft robot

Tester-> recipe++: CanCraft(s)
recipe -> s++: GetAsteroid()

s --> recipe--: a
recipe -> s++: GetInventory()

s --> recipe--: inv

recipe -> inv++: getItems()
inv --> recipe--: items

recipe -> a++: GetInventory()
a --> recipe--: inventory

recipe -> inventory++: getItems()
inventory --> recipe--: aItems

group loop: input check[for each i in recipe.input]

    group loop [for each item in items]
        recipe -> item++: Satisfies(i)
        item --> recipe--: x
    end

    group loop [for each item in aItems]
        recipe -> aItem++: Satisfies(i)
        aItem --> recipe--: y
    end

    group opt interrupt [if (x+y) < i.amount]
        recipe --> Tester: false
    end
    note right
    x+y is not enough to satisfy recipe, it will happen in at least one of the items. 
    When it's true, the function will not continue, and immediately return with false
    end note
end
 


@enduml