@startuml
rectangle "recipe: SpaceStationRecope" as recipe 
rectangle "s: SpaceShip" as s 
rectangle "inventory: Inventory" as inventory 
rectangle "asteroid: Asteroid" as asteroid
rectangle "inv:Inventory" as inv 
rectangle "i: Item" as i
rectangle "station: SpaceStation" as station 
rectangle "scene: Scene" as scene
rectangle "mgr: GameManager" as mgr

title SpaceShip can craft station \n 

recipe -- s: 1. GetAsteroid() \n <---- \n 2. a \n - - -> \n 3. GetInventory() \n <---- \n 4. inv \n - - -> \n 


recipe -left- inventory: 5. RemoveItem(i) \n <---- \n 6. x \n - - -> 

recipe -- i: 7.Reduce(x) \n ---->

recipe -- asteroid: 8. GetInventory() \n <---- \n 9. inv \n - - -> 

recipe -- inv: 10. RemoveItem(i) \n ----> \n 10. y \n <- - - 

recipe -down- recipe: 12. MakeResult(s)\n | \nv

recipe -- station: 12.1 SpaceStation(asteroid)\n ---->

station--asteroid: 12.1.1 AddBuilding(station)\n <---- \n 12.1.2 GetScene()\n <---- \n 12.1.3 scene\n - - ->

station-- scene: 12.1.4 GetManager()\n <---- \n 12.1.5 mgr\n - - ->

station --mgr: 12.1.6 EndGame()\n ---->




@enduml