@startuml
rectangle "recipe: SpaceStationRecope" as recipe 
rectangle "s: SpaceShip" as s 
rectangle "inventory: Inventory" as inventory 
rectangle "asteroid: Asteroid" as asteroid
rectangle "inv:Inventory" as inv 
rectangle "rItem: Item" as rItem
rectangle "station: SpaceStation" as station 
rectangle "item: Item" as item
rectangle "aItem: Item" as aItem
rectangle "scene: Scene" as scene
rectangle "mgr: GameManager" as mgr

title SpaceShip can craft station \n 

recipe -- s: 1. GetAsteroid() \n ----> \n 2. a \n <- - - \n 3. GetInventory() \n ----> \n 4. inv \n <- - - \n 


recipe -left- inventory: 5. RemoveItem(rItem) \n <---- \n 6. x \n - - -> 

inventory -- item: 5.1 Satisfies(rItem) \n <---- \n 5.2 x \n - - -> \n 5.3 Reduce(x) \n <---- \n 

recipe -- rItem: 7.Reduce(x) \n ---->

recipe -- asteroid: 8. GetInventory() \n <---- \n 9. inv \n - - -> 

recipe -- inv: 10. RemoveItem(rItem) \n <---- \n 11. y \n - - -> 

inv -- aItem: 10.1 Satisfies(rItem) \n <---- \n 10.2 x \n - - -> \n 10.3 Reduce(x) \n <---- \n 

recipe -down- recipe: 12. MakeResult(s)\n | \nv

recipe -- station: 12.1 SpaceStation(asteroid)\n ---->

station--asteroid: 12.1.1 AddBuilding(station)\n <---- \n 12.1.2 GetScene()\n <---- \n 12.1.3 scene\n - - ->

station-- scene: 12.1.4 GetManager()\n ----> \n 12.1.5 mgr\n <- - -

station --mgr: 12.1.6 EndGame()\n <----




@enduml