@startuml
hide footbox
title Place first gate


actor Tester as Tester

participant tgItem as tgItem <<TeleportGateItem>>
participant ship as ship <<SpaceShip>>

participant tg as tg <<TeleportGate>>

Tester -> tgItem : Activate(ship)
activate tgItem

tgItem -> ship ++ : GetCurrentAsteroid()

ship --> tgItem -- : a = result

create tg
tgItem --> tg : p = TeleportGate(a)

tgItem -> tgItem : pair = p

tgItem --> Tester 
deactivate tgItem

@enduml