@startuml
autonumber "0:"
hide footbox

title Make Solar Flare

actor Tester as Tester

participant "gm : GameManager" as gm

Tester -> gm : QueueSolarStorm()
activate gm

gm -> gm : CreateStormOn = true;

gm --> Tester

deactivate gm

@enduml