@startuml


title Insert TeleportGate to SSinventory

actor ss as "ss: SpaceShip"

participant inventory as "ss.inventory:SSinventoryetory"
participant list as "ss.inventory.tgs:List<Item>"
participant tg as "tg:TeleportGateItem"

ss -> inventory: insertItem(item)
activate inventory

opt if ss.inventory.count < 10
    inventory -> list : add(Item)
    activate list
    list --> inventory
    deactivate
    inventory --> ss : true

end
opt if ss.inventory.count >=10
    inventory --> ss : false
end
deactivate

@enduml