@startuml


title Insert Item to InfiniteInventory

actor ufo as "ufo: UFO"

participant inv as "ufo.inv:InfiniteInvetory"
participant item as "item:Item"

ufo -> inv: insertItem(item)

inv --> ufo : true

@enduml