@startuml
'autonumber "0:"
skinparam linestyle ortho

actor Tester as Tester
rectangle "R : Robot" as S
rectangle "currentAsteroid : Asteroid" as ca

Tester --> S: "1 : -> ExitHiding()" "4 : <--"
S --> ca: "2 : -> Exit(R)" "3 : <--"


@enduml