@startuml
hide footbox
title Add Listener

actor Player as player
participant "notify: INotifyPropertyChanged" as notify
participant "statechanged: StateChangedListener" as statechanged

player -> notify++: addListener(statechanged)
notify -> notify++: listeners.add(statechanged)
notify --> player--: return

@enduml