@startuml
hide footbox
title Add Listener

actor Tester as tester
participant "notify: INotifyPropertyChanged" as notify
participant "statechanged: StateChangedListener" as statechanged

tester -> notify++: addListener(statechanged)
notify -> notify++: listeners.add(statechanged)
notify --> tester--: return

@enduml