@startuml
hide footbox
title Manager notifies Listeners 

actor Tester as tester
participant "notify: GameManager" as notify
collections "listener: StateChangedListener" as listener

tester -> notify++: notifyListeners()
group loop: [for each listener in listeners]
    notify -> listener++: statechanged()
    listener --> notify--: return
end
notify --> tester--: return


@enduml