@startuml
hide footbox
title Engine notifies Listeners

actor Player as player
participant "notify: Engine" as notify
collections "listener: StateChangedListener" as listener

player -> notify++: notifyListeners()
group loop: [for each listener in listeners]
    notify -> listener++: statechanged()
    listener --> notify--: return
end
notify --> player--: return


@enduml