@startuml

actor Tester as Tester
participant s as s <<SpaceShip>>
participant recipe as recipe <<RobotRecipe>>


title SpaceShip can't craft robot

Tester -> s++: Craft(recipe)

s-> recipe++: CanCraft(s)
recipe --> s --: false

s--> Tester: false

@enduml