@startuml
hide footbox
title Ship mine from asteroid


actor Tester as Tester


participant ship as ship <<SpaceShip>>

participant a as a <<Asteroid>>

participant a_inv as a_inv<<AszteroidInventory>>

participant ship_inv as ship_inv<<SSInventory>>

Tester -> ship : Mine()
activate ship

ship -> a ++: Mine(ship)

a -> a_inv++ : Mine()
a_inv --> a--: item

a --> ship--: item

ship->ship_inv++: InsertItem(i)
ship_inv --> ship--: true

ship --> Tester
deactivate ship

@enduml