@startuml
hide footbox
title Ship mine when asteroid is exploded


actor Tester as Tester


participant ship as ship <<SpaceShip>>

participant a as a <<Asteroid>>

Tester -> ship : Mine()
activate ship

ship -> a ++: Mine(ship)

a --> ship --: null

ship --> Tester
deactivate ship

@enduml