@startuml
hide footbox
title UFO mine from asteroid


actor Tester as Tester


participant ufo as ufo <<UFO>>

participant a as a <<Asteroid>>

participant a_inv as a_inv<<AszteroidInventory>>

participant ufo_inv as ufo_inv<<InfiniteInventory>>

Tester -> ufo : Mine()
activate ufo

ufo -> a ++: Mine(ship)

a -> a_inv++ : Mine()
a_inv --> a--: item

a --> ufo--: item

ufo->ufo_inv++: InsertItem(i)
ufo_inv --> ufo--: true

ufo --> Tester
deactivate ufo

@enduml