@startuml
hide empty description

state Normal
[*] --> Normal

Normal -> Crazy : SolarFlare
state Crazy{
    state Standby
    state Move

    Standby --> Move : Chance
}


caption A teleport kapu-t ha napszél éri akkor elkezd mozogni.\n Minden körben egy véletlen segítségével dönti el, hogy fog e mozogni



@enduml