@startuml

actor Tester as Tester
participant s as s <<SpaceShip>>
participant recipe as recipe <<SpaceStationRecipe>>


title SpaceShip can't craft space station

Tester -> s++: Craft(recipe)

s-> recipe++: CanCraft(s)
recipe --> s --: false

s--> Tester: false

@enduml