@startuml
actor Tester as Tester<<SpaceShip>>
participant recipe as recipe <<SpaceStationRecipe>>
participant s as s <<SpaceShip>>
participant inventory as inventory <<Inventory>>
participant asteroid as asteroid <<Asteroid>>
participant inv as inv <<Inventory>>
collections item as item <<Item>>
participant station as station <<SpaceStation>>
participant scene as scene <<Scene>>
participant mgr as mgr <<GameManager>>


title SpaceShip can craft space station

Tester-> recipe++: Craft(s)

recipe -> s++: GetAsteroid()
s --> recipe--: a

recipe -> s++: GetInventory()
s --> recipe--: inv

group loop: input check[for each item in recipe.input]

    recipe -> inventory++: RemoveItem(item)
    inventory-->recipe--: x

    recipe -> item++: Reduce(x)
    item --> recipe--: 

    group opt [not satisfied]
        recipe -> asteroid++: GetInventory()
        asteroid --> recipe--: inv

        recipe -> inv++: RemoveItem(i)
        inv--> recipe--: y
    end
end
recipe -> recipe++: MakeResult(s)

recipe --> station: <<create>> SpaceStation(asteroid)
station -> station++:  SpaceStation(asteroid)

note right
konstruktorhívás belseje
end note

station -> asteroid++: AddBuilding(station)
asteroid --> station--: 

station -> asteroid++: GetScene()
asteroid --> station--: scene

station -> scene++: GetManager()
scene --> station--: mgr

station -> mgr++: EndGame()
mgr --> station--: 

station-->recipe--:


recipe --> Tester: 

caption A recept levonja a nyersanyagokat a megfelelő helyekről (telepes vagy aszteroida raktárából, kapacitástól függően), \n majd elkészíti az űrállomást és elhelyezi a megfelelő aszteroidán. Az űrállomás konstruktora jelzi a játékmenedzsernek, hogy felépült az űrállomás, ami a játék végét jelenti. 

@enduml