@startuml
hide footbox
title SpaceShip place resource when core is not full

actor Tester as Tester

participant s as s <<SpaceShip>>
participant currentAsteroid as currentAsteroid <<Asteroid>>
participant currentAsteroid.inventory as currentAsteroid.inventory <<Inventory>>
participant s.inventory as s.inventory <<Inventory>>
participant item as item <<Item>>

Tester -> s : PlaceItem(item)
activate s

s -> currentAsteroid ++: PlaceItem(item)

currentAsteroid -> currentAsteroid.inventory ++: TryInsertItem(item)

currentAsteroid.inventory --> currentAsteroid --: true

currentAsteroid -> currentAsteroid.inventory ++: InsertItem(item)

currentAsteroid.inventory --> currentAsteroid --: true

currentAsteroid --> s --: true

s -> s.inventory ++: RemoceItem(item)

s.inventory --> s --

s--> Tester : true
deactivate s
@enduml

