@startuml
hide footbox
title SpaceShip place resource when core is full

actor Tester as Tester

participant s as s <<SpaceShip>>
participant currentAsteroid as currentAsteroid <<Asteroid>>
participant inventory as inventory <<Inventory>>
participant item as item <<Item>>

Tester -> s : PlaceItem(item)
activate s

s -> currentAsteroid ++: PlaceItem(item)

currentAsteroid -> inventory ++: TryInsertItem(item)

inventory --> currentAsteroid --: false

currentAsteroid --> s --: false

s--> Tester : false
deactivate s
@enduml

