@startuml
hide footbox
autonumber "0:"
skinparam sequenceMessageAlign center

title SpaceShip drill when asteroid exploded

actor Tester as Tester
participant "v : Vessel" as v
participant "currentAsteroid : Asteroid" as currentAsteroid

Tester -> v : Drill()
activate v

v -> currentAsteroid : Drill()
activate currentAsteroid

currentAsteroid -> currentAsteroid : crustSize --

currentAsteroid --> v 
deactivate currentAsteroid

v --> Tester
deactivate v

@enduml