@startuml

actor Tester as Tester
participant s as s <<SpaceShip>>
participant recipe as recipe <<TeleportGateRecipe>>


title SpaceShip can't craft teleport gate

Tester -> s++: Craft(recipe)

s-> recipe++: CanCraft(s)
recipe --> s --: false

s--> Tester: false

@enduml