@startuml
rectangle "s: SpaceShip" as s
rectangle “recipe: TeleportGateRecipe” as recipe

title SpaceShip can't craft teleport gate \n 

s -right- recipe: 1: CanCraft(s) \n ----> \n 2: false \n <- - - -  


@enduml