@startuml

actor Tester as Tester
participant s as s <<SpaceShip>>
participant recipe as recipe <<TeleportGateRecipe>>


title SpaceShip can craft teleport gate

Tester -> s++: Craft(recipe)

s-> recipe++: CanCraft(s)
recipe --> s --: true

s-> recipe++: Craft(s) 
recipe-->s--: 

s--> Tester: true




@enduml