@startuml
!include ../../style.puml

title SpaceShip place resource when asteroid exploded

actor Tester as Tester
participant "s : SpaceShip" as s
participant "item : Item" as item

Tester -> s : PlaceItem()
activate s

s --> Tester : false
deactivate s

@enduml