name: Build Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - uses: xu-cheng/latex-action@v2
      with:
        root_file: "projlab.tex"
        
    - uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: projlab.pdf
