name: Build Docs

on: [push]

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2.3.4
    
    - name: Get changed UML files
      id: getfile
      run: |
        echo "::set-output name=files::$(find . | grep ${{ env.UML_FILES }} | xargs)"

    - name: UML files considered echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}

    - name: Generate eps Diagrams
      uses: cloudbees/plantuml-github-action@master
      continue-on-error: true
      with:
          args: -v -charset UTF-8 -teps ${{ steps.getfile.outputs.files }}

    - name: Generate latex from mdj
      run: |
          chmod +x ./.bin/UMLTemplater/UMLTemplater
          ./.bin/UMLTemplater/UMLTemplater --input ./DesignModel.mdj --output ./docs/2_Project/out.tex


    - name: Generate diagram includes
      run: |
          chmod +x ./.bin/UMLTemplater/UMLTemplater
          ./.bin/UMLTemplater/UMLTemplater svg ./docs/3_Project/svg ./DesignModel.mdj ./docs/3_Project/diagrams.tex


#    - name: Compile Main docs
#      uses: jheubuch/latex-action@2.2.1
#      with:
#        root_file: "projlab.tex"
#        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape
        
#    - name: Compile 1. milestone
#      uses: jheubuch/latex-action@2.2.1
#      with:
#        working_directory: ./docs/1_Project
#        root_file: Project_desc.tex
#        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape

#    - name: Compile 2. milestone
#      uses: jheubuch/latex-action@2.2.1
#      with:
#        working_directory: ./docs/2_Project
#        root_file: Models.tex
#        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape  

#    - name: Compile 3. milestone
#      uses: jheubuch/latex-action@2.2.1
#      with:
#        working_directory: ./docs/3_Project
#        root_file: Models-2.tex
#        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape     

#    - name: Compile 4. milestone
#      uses: jheubuch/latex-action@2.2.1
#      with:
#        working_directory: ./docs/Skeleton
#        root_file: Skeleton.tex
#        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape

#    - name: Compile 5. milestone
#      uses: jheubuch/latex-action@2.2.1
#      with:
#        working_directory: ./docs/bead06
#        root_file: 06doc.tex
#        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape

#    - name: Compile 6. milestone
#      uses: jheubuch/latex-action@2.2.1
#      with:
#        working_directory: ./docs/bead07
#        root_file: 07doc.tex
#        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape

    - name: Compile 7. milestone
      uses: jheubuch/latex-action@2.2.1
      with:
        working_directory: ./docs/bead08
        root_file: 08doc.tex
        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape

    - name: Compile 8. milestone
      uses: jheubuch/latex-action@2.2.1
      with:
        working_directory: ./docs/bead10
        root_file: 10doc.tex
        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape

    - name: Compile 11. milestone
      uses: jheubuch/latex-action@2.2.1
      with:
        working_directory: ./docs/bead11
        root_file: 11doc.tex
        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape        

    - uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: |
          build/projlab.pdf
          docs/**/build/*.pdf
