name: Build Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - name: Compile Main docs
      uses: xu-cheng/latex-action@v2
      with:
        root_file: "projlab.tex"
        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -output-directory=build --shell-escape
        latexmk_shell_escape: true
        
    - name: Compile 1 milestone
      uses: dante-ev/latex-action@master
      with:
        working_directory: ./docs/1_Project
        root_file: Project_desc.tex

    - uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: 
        path: |
          build/projlab.pdf
          docs/**/build/*.pdf
